export { default as HomePage } from './client/home/HomePage'
export { default as IntroPage } from './client/introduction/IntroPage'
export { default as GenusPage } from './client/genus/GenusPage'
export { default as SpeciesPage } from './client/species/SpeciesPage'

export { default as Login } from './admin/auth/Login'
export { default as ResetPassword } from './admin/auth/ResetPassword'
export { default as Dashboard } from './admin/dashboard/Dashboard'
export { default as UserManager } from './admin/user/UserManager'
export { default as GenusManager } from './admin/genus/GenusManager'
export { default as SpeciesManager } from './admin/species/SpeciesManager'
export { default as AddEditSpecies } from './admin/species/AddEditPage'

export { default as NotFound } from './other/NotFound'
export { default as Error500 } from './other/Error500'